apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-app
  name: auth-service
  namespace: default
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: auth-app
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-app-deployment
  labels:
    app: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
        - name: auth-app
          image: gcr.io/ic-cloud-native/auth-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080